# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 12:01
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170711_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
